version: "3"
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
